version: '3.8'

services:
  postgresdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"

  my-web-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgresdb